/*------------------------------------------------------
 
	XML File that loads .fnt files generated by Bitmap Font Generator	
	http://www.angelcode.com/products/bmfont/

	It produces a texture atlas asset which can be used for textured fonts (when combined with a texture)


 -------------------------------------------------------*/
#pragma once

#include "TFile.h"
#include "TFileXml.h"
#include <TootleAsset/TAtlas.h>



namespace TLFileSys
{
	class TFileFnt;	
};



//---------------------------------------------------------
//	
//---------------------------------------------------------
class TLFileSys::TFileFnt : public TLFileSys::TFileXml
{
public:
	TFileFnt(TRefRef FileRef,TRefRef FileTypeRef);
	
	virtual SyncBool	ExportAsset(TPtr<TLAsset::TAsset>& pAsset,Bool& Supported);

protected:
	SyncBool			ImportChar(TXmlTag& Tag,TLAsset::TAtlas& Atlas,const float2& ImageScale,float GlyphScale,u32 LineBaseLine);
	SyncBool			ImportFont(TXmlTag& Tag,TLAsset::TAtlas& Atlas);
};


